# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfigForm(object):
    def setupUi(self, ConfigForm):
        ConfigForm.setObjectName("ConfigForm")
        ConfigForm.resize(617, 195)
        self.verticalLayout = QtWidgets.QVBoxLayout(ConfigForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(ConfigForm)
        font = QtGui.QFont()
        font.setFamily("方正黑体简体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.ifProxyCheckBox = QtWidgets.QCheckBox(ConfigForm)
        self.ifProxyCheckBox.setObjectName("ifProxyCheckBox")
        self.horizontalLayout.addWidget(self.ifProxyCheckBox)
        self.testProxyButton = QtWidgets.QPushButton(ConfigForm)
        self.testProxyButton.setEnabled(False)
        self.testProxyButton.setObjectName("testProxyButton")
        self.horizontalLayout.addWidget(self.testProxyButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(ConfigForm)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(ConfigForm)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.proxyIpLineEdit = QtWidgets.QLineEdit(ConfigForm)
        self.proxyIpLineEdit.setEnabled(False)
        self.proxyIpLineEdit.setObjectName("proxyIpLineEdit")
        self.gridLayout.addWidget(self.proxyIpLineEdit, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(ConfigForm)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.proxyPortLineEdit = QtWidgets.QLineEdit(ConfigForm)
        self.proxyPortLineEdit.setEnabled(False)
        self.proxyPortLineEdit.setObjectName("proxyPortLineEdit")
        self.gridLayout.addWidget(self.proxyPortLineEdit, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(ConfigForm)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 85, 0);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(ConfigForm)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 100)
        self.verticalLayout.setStretch(3, 1)

        self.retranslateUi(ConfigForm)
        self.ifProxyCheckBox.stateChanged['int'].connect(ConfigForm.updateConnectButtonStatus)
        self.testProxyButton.clicked.connect(ConfigForm.connectProxy)
        self.pushButton.clicked.connect(ConfigForm.saveConf)
        QtCore.QMetaObject.connectSlotsByName(ConfigForm)

    def retranslateUi(self, ConfigForm):
        _translate = QtCore.QCoreApplication.translate
        ConfigForm.setWindowTitle(_translate("ConfigForm", "设置"))
        self.label.setText(_translate("ConfigForm", "代理设置"))
        self.ifProxyCheckBox.setText(_translate("ConfigForm", "启用代理"))
        self.testProxyButton.setText(_translate("ConfigForm", "测试代理"))
        self.label_2.setText(_translate("ConfigForm", "代理IP"))
        self.label_3.setText(_translate("ConfigForm", "代理端口"))
        self.pushButton.setText(_translate("ConfigForm", "保存"))
