# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'helpForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HelpForm(object):
    def setupUi(self, HelpForm):
        HelpForm.setObjectName("HelpForm")
        HelpForm.resize(621, 377)
        self.verticalLayout = QtWidgets.QVBoxLayout(HelpForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(HelpForm)
        font = QtGui.QFont()
        font.setFamily("方正黑体简体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line = QtWidgets.QFrame(HelpForm)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(HelpForm)
        self.plainTextEdit.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("方正黑体简体")
        font.setPointSize(11)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)

        self.retranslateUi(HelpForm)
        QtCore.QMetaObject.connectSlotsByName(HelpForm)

    def retranslateUi(self, HelpForm):
        _translate = QtCore.QCoreApplication.translate
        HelpForm.setWindowTitle(_translate("HelpForm", "Dialog"))
        self.label.setText(_translate("HelpForm", "使用说明"))
        self.plainTextEdit.setPlainText(_translate("HelpForm", "（1）在URL框内输入对应的URL    \n"
"\n"
"（2）勾选需要数量的输入，输入内容会按照鱼叉模式（Pitchfork）构建     \n"
"\n"
"（3）调整自动生成的输入格式，每个输入框的输入使用$%$输入值1$%$、$%$输入值2$%$ 表示，插入形式与brupsuite爆破报文形式类似  \n"
"\n"
"（4）调整js处理函数标签内自动生成的js代码，process函数名不能调整，    \n"
"\n"
"（5）点击运行按钮，若一切正常，输出结果将会显示在 结果 标签处，否则结果处会显示None，这时候请检查js处理函数处的输入是否符合js语法    \n"
"\n"
"PS:如使用遇到问题请提交至github，地址如下：\n"
"https://github.com/abcd1234564499sc/runJSFunctionByUrl"))
